server:
  port: 18080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #define routing rules
      routes:
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - RewritePath=/api/customer/(?<segment>.*), /$\{segment}

        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - RewritePath=/api/visit/(?<segment>.*), /$\{segment}
            # - name: CircuitBreaker
            #   args:
            #     name: visits-cb
            #     fallbackUri: forward:/fallback/visits

        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - RewritePath=/api/vet/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:18761/eureka/

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      visits-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50 #50% of last 10 request
        wait-duration-in-open-state: 10s #Wait 10s before HALF_OPEN
        permitted-number-of-calls-in-half-open-state: 3 #Allow 3 test requests
        automatic-transition-from-open-to-half-open-enabled: true