server:
  port: 18080 #default-app port

spring:
  application:
    name: not-set # default app name
  zipkin:
    base-url: http://host.docker.internal:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:18180/realms/petclinic

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:18761/eureka/
    instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0 #100% request for tracing