server:
  port: 8080 #default-app port

spring:
  application:
    name: not-set # default app name

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true