server:
  port: 0 # random port

spring:
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:19092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/