server:
  port: 18083

spring:
  application:
    name: vets-service
  datasource:
    url: jdbc:hsqldb:mem:vetsdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: host.docker.internal
      port: 6379
    cache:
      type: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:18761/eureka/