server:
  port: 8083

spring:
  datasource:
    url: jdbc:hsqldb:mem:vetsdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/