server:
  port: 8084
spring:
  application:
    name: visits-service
  datasource:
    url: jdbc:hsqldb:mem:ownersdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/